/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/downBad.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/downBad.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.crushies_portfolio.geometry} material={materials['Steel_-_Satin']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/downBad.glb')
